# Generated by Django 2.2.4 on 2019-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.SlugField(max_length=200)),
                ('url', models.URLField()),
                ('date_submited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
