# Generated by Django 2.2.4 on 2019-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
